### ISSUE TITLE
Does BSD-3 Clause Comply with GPLv2 License ?

### ISSUE THREAD

**Issue by antony-jr** [antony-jr/QAIUpdateInformation#1]
@probonopd I replaced the **objdump** code to **light_elf.h** from **AppImageKit**  , Do I still voilate the GPL ?
Since **AppImageKit** is **MIT Licensed** , I think my code also , does not voilate the GPL. 
**Am I wrong?**

**Comment by probonopd** [comment]
If you are not using any GPL code in this project, then this project will not violate the GPL.

What is the reason that you are choosing BSD rather than MIT?

**Comment by antony-jr** [comment]
I used **light_elf.h** from **AppImageKit/src/** , does that count as **GPL code** , it is licensed under **GPLv2**.

I **use** BSD , because its my personal preference , I can relicence if you want , to **MIT**.

**Comment by probonopd** [comment]
Thanks for pointing this out. We should replace this by something non-GPL. cc @teras

Reference:
https://github.com/AppImage/AppImageKit/commit/c7fe818a6088201de2d87c18e3153162916dcf79

**Comment by antony-jr** [comment]
@probonopd Here is a elf parser with **NON-GPL** license , it uses a license that is not official published , this license allows to use it like **MIT** but it forbids us from **compiling** with any **GPL Licensed Lib**. https://github.com/macmade/ELFDump , currently 64 bit available , not working with 32 bit **AppImages**.

**Comment by antony-jr** [comment]
I think we could modify it to support 32 bit **AppImages**.

**Comment by antony-jr** [comment]
@probonopd Found a alternative to **elf.h** , **elf_abi.h** licensed under **BSD**. Satifies all the requirements , better than **elfdump**. Please see https://github.com/McIkye/tools/blob/master/include/elf_abi.h

**Comment by antony-jr** [comment]
Changed my code with **elf_abi.h** , now works good , **without GPL licensed** code.
